[camera]
background_color = [
    1.0,
    1.0,
    1.0,
]
look_at = [
    1.5,
    1.5,
    0.0,
]
look_from = [
    1.5,
    1.5,
    3.0,
]
field_of_view = 80.0
samples_per_pixel = 200
ray_max_bounces = 50

[[textures]]

[textures.SolidColor]
color = [
    1.0,
    0.0,
    0.0,
]

[[textures]]

[textures.SolidColor]
color = [
    0.0,
    1.0,
    0.0,
]

[[materials]]

[materials.Lambertian]
texture = 0

[[materials]]

[materials.Lambertian]
texture = 1

[[objects]]

[objects.Quad]
point = [
    0.0,
    0.0,
    0.0,
]
u = [
    1.0,
    0.0,
    0.0,
]
v = [
    0.0,
    1.0,
    0.0,
]
material = 0

[[objects]]

[objects.Translate]
offset = [
    -1.0,
    0.0,
    0.0,
]

[[objects]]

[objects.Scale]
factor = 2

[[objects]]

[objects.Quad]
point = [
    1.0,
    0.0,
    0.0,
]
u = [
    1.0,
    0.0,
    0.0,
]
v = [
    0.0,
    1.0,
    0.0,
]
material = 1
