[package]
name = "nr-ray-tracer-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
glam = { version = "0.30.2", features = ["serde"] }
image = "0.25.6"
noise = "0.9.0"
rand = "0.9.1"
rand_chacha = "0.9.0"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_test = "1.0.177"
serde_with = "3.12.0"
